# Site settings
author: Tharon P Weighill
title: Delicious Bytes
header-img: img/home-bg.png
email: tharonweighill@gmail.com
copyright_name: Tharon P Weighill
description: > # this means to ignore newlines until "baseurl:"
  Chef to Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TharonWeighill

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
